trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AzWebMediaManagerMHL


stages:
- stage: Build
  displayName: 'Build the project'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install dependencies and build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive files'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(serviceConnectionProduction)'
        appName: '$(webAppNameProduction)'
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        displayName: 'Deploy to Azure Web App'
