trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'PROD'
  values:
    - 'PROD'
    - 'DEV'

variables:
- ${{ if contains(parameters['environment'], 'DEV') }}:
  - group: "AzMHLMediaManagerDev"
- ${{ if contains(parameters['environment'], 'PROD') }}:
  - group: "AzMHLMediaManagerProduction"


stages:
- stage: Build
  displayName: 'Build the project'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install dependencies and build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive files'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(serviceConnection)'
        appName: '$(webAppName)'
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        displayName: 'Deploy to Azure Web App'
